# TE - Visualização de Dados

## Análise exploratória do dataset LEM consolidado — 2021 a 2025

Este notebook realiza uma análise exploratória **somente sobre o dataset já padronizado** `lem_consolidado_2021_2025.csv`.

O objetivo desta etapa é verificar a estrutura, a qualidade e as principais características do conjunto de dados antes da definição final das visualizações interativas da solução.

## 1. Importação das bibliotecas

In [13]:
import pandas as pd
import numpy as np
from pathlib import Path

import matplotlib.pyplot as plt
import seaborn as sns

from data_profiling import ProfileReport

sns.set_theme(style="whitegrid")
plt.rcParams["figure.figsize"] = (12, 6)

## 2. Leitura do dataset padronizado

O código abaixo procura o arquivo `lem_consolidado_2021_2025.csv` dentro de `dados_tratados/`;

In [14]:
possiveis_caminhos = [
    Path("dados_tratados/lem_consolidado_2021_2025.csv"),
    Path("../dados_tratados/lem_consolidado_2021_2025.csv"),
]

caminho_dataset = None

for caminho in possiveis_caminhos:
    if caminho.exists():
        caminho_dataset = caminho
        break

if caminho_dataset is None:
    raise FileNotFoundError("Arquivo lem_consolidado_2021_2025.csv não encontrado. Verifique o caminho do dataset.")

print(f"Dataset encontrado em: {caminho_dataset}")

df = pd.read_csv(caminho_dataset)
df.head()

Dataset encontrado em: dados_tratados/lem_consolidado_2021_2025.csv

,ano,mes_numero,mes,data,categoria,subcategoria,indicador,indicador_completo,valor
0,2021,1,JAN,2021-01-01,EDUCAÇÃO,Ensino EJA,aguardando vaga,Ensino EJA - aguardando vaga,0.0
1,2021,1,JAN,2021-01-01,EDUCAÇÃO,Ensino EJA,matriculados,Ensino EJA - matriculados,0.0
2,2021,1,JAN,2021-01-01,EDUCAÇÃO,Ensino infantil,aguardando vaga,Ensino infantil - aguardando vaga,3.0
3,2021,1,JAN,2021-01-01,EDUCAÇÃO,Ensino infantil,matriculados,Ensino infantil - matriculados,2.0
4,2021,1,JAN,2021-01-01,EDUCAÇÃO,Ensino regular,aguardando vaga,Ensino regular - aguardando vaga,3.0

## 3. Ajuste de tipos e visão inicial

A coluna `data` é convertida para formato de data para permitir verificações temporais. As demais colunas são mantidas conforme o processamento anterior.

In [15]:
df["data"] = pd.to_datetime(df["data"], errors="coerce")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1862 entries, 0 to 1861
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ano                 1862 non-null   int64
 1   mes_numero          1862 non-null   int64
 2   mes                 1862 non-null   object
 3   data                1862 non-null   datetime64[ns]
 4   categoria           850 non-null    object
 5   subcategoria        436 non-null    object
 6   indicador           1862 non-null   object
 7   indicador_completo  1862 non-null   object
 8   valor               1862 non-null   float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(5)
memory usage: 131.1+ KB

In [16]:
df.head(10)

,ano,mes_numero,mes,data,categoria,subcategoria,indicador,indicador_completo,valor
0,2021,1,JAN,2021-01-01,EDUCAÇÃO,Ensino EJA,aguardando vaga,Ensino EJA - aguardando vaga,0.0
1,2021,1,JAN,2021-01-01,EDUCAÇÃO,Ensino EJA,matriculados,Ensino EJA - matriculados,0.0
2,2021,1,JAN,2021-01-01,EDUCAÇÃO,Ensino infantil,aguardando vaga,Ensino infantil - aguardando vaga,3.0
3,2021,1,JAN,2021-01-01,EDUCAÇÃO,Ensino infantil,matriculados,Ensino infantil - matriculados,2.0
4,2021,1,JAN,2021-01-01,EDUCAÇÃO,Ensino regular,aguardando vaga,Ensino regular - aguardando vaga,3.0
5,2021,1,JAN,2021-01-01,EDUCAÇÃO,Ensino regular,matriculados,Ensino regular - matriculados,12.0
6,2021,1,JAN,2021-01-01,EDUCAÇÃO,SCFV,"Outros: Reforço escolar, psicopedagoga, trabal...","SCFV - Outros: Reforço escolar, psicopedagoga,...",0.0
7,2021,1,JAN,2021-01-01,EDUCAÇÃO,SCFV,aguardando vaga,SCFV - aguardando vaga,0.0
8,2021,1,JAN,2021-01-01,EDUCAÇÃO,SCFV,matriculados,SCFV - matriculados,0.0
9,2021,1,JAN,2021-01-01,PROFISSIONALIZAÇÃO,NaN,Encaminhados para curso profissionalizante,Encaminhados para curso profissionalizante,0.0

## 4. Perfilamento automático com ydata-profiling

O `ydata-profiling` gera uma visão automática sobre o dataset, incluindo tipos de variáveis, valores ausentes, distribuições, frequências de categorias, estatísticas descritivas e alertas de qualidade.

Aqui o relatório é exibido diretamente no notebook, sem exportar HTML.

In [17]:
profile = ProfileReport(
    df,
    title="Perfil exploratório do dataset LEM consolidado — 2021 a 2025",
    explorative=True,
    minimal=True
)

profile.to_notebook_iframe()

100%|██████████| 9/9 [00:00<00:00, 136770.78it/s]0:00, 143.80it/s, Describe variable: valor]
Summarize dataset: 100%|██████████| 15/15 [00:00<00:00, 286.42it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:01<00:00,  1.05s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.23it/s]

## 5. Resumo estrutural do dataset

In [18]:
resumo_estrutura = pd.DataFrame({
    "métrica": [
        "Quantidade de linhas",
        "Quantidade de colunas",
        "Anos distintos",
        "Meses distintos",
        "Categorias distintas",
        "Subcategorias distintas",
        "Indicadores distintos",
        "Indicadores completos distintos"
    ],
    "valor": [
        df.shape[0],
        df.shape[1],
        df["ano"].nunique(),
        df["mes"].nunique(),
        df["categoria"].nunique(),
        df["subcategoria"].nunique(dropna=True),
        df["indicador"].nunique(),
        df["indicador_completo"].nunique()
    ]
})

resumo_estrutura

                           métrica  valor
0             Quantidade de linhas   1862
1            Quantidade de colunas      9
2                   Anos distintos      5
3                  Meses distintos     12
4             Categorias distintas      3
5          Subcategorias distintas      4
6            Indicadores distintos     27
7  Indicadores completos distintos     33

## 6. Qualidade dos dados: valores ausentes

In [19]:
nulos = (
    df.isna().sum()
    .reset_index()
    .rename(columns={"index": "coluna", 0: "qtd_nulos"})
)

nulos["percentual_nulos"] = (nulos["qtd_nulos"] / len(df) * 100).round(2)
nulos.sort_values("percentual_nulos", ascending=False)

               coluna  qtd_nulos  percentual_nulos
5        subcategoria       1426             76.58
4           categoria       1012             54.35
0                 ano          0              0.00
1          mes_numero          0              0.00
2                 mes          0              0.00
3                data          0              0.00
6           indicador          0              0.00
7  indicador_completo          0              0.00
8               valor          0              0.00

In [20]:
nulos_plot = nulos.sort_values("percentual_nulos", ascending=True)

plt.figure(figsize=(10, 5))
plt.barh(nulos_plot["coluna"], nulos_plot["percentual_nulos"])
plt.xlabel("Percentual de valores ausentes (%)")
plt.ylabel("Coluna")
plt.title("Percentual de valores ausentes por coluna")
plt.show()

/var/folders/m9/41dfdw417w50w33q_xckq5qh0000gp/T/ipykernel_15608/240065033.py:8: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## 7. Qualidade dos dados: duplicatas

In [21]:
qtd_duplicatas = df.duplicated().sum()
percentual_duplicatas = round(qtd_duplicatas / len(df) * 100, 2)

pd.DataFrame({
    "métrica": ["Linhas duplicadas", "Percentual de duplicatas"],
    "valor": [qtd_duplicatas, percentual_duplicatas]
})

                    métrica  valor
0         Linhas duplicadas    0.0
1  Percentual de duplicatas    0.0

## 8. Cobertura temporal do dataset

Esta seção verifica se o dataset possui registros distribuídos entre os anos e meses esperados.

In [22]:
cobertura_ano = (
    df.groupby("ano")
    .agg(
        qtd_registros=("valor", "count"),
        qtd_meses=("mes", "nunique"),
        qtd_indicadores=("indicador_completo", "nunique"),
        total_valor=("valor", "sum")
    )
    .reset_index()
)

cobertura_ano

    ano  qtd_registros  qtd_meses  qtd_indicadores  total_valor
0  2021            389         12               33       2335.0
1  2022            388         12               33       2360.0
2  2023            304         12               30       3760.0
3  2024            393         12               33       3253.0
4  2025            388         12               33       3267.0

In [23]:
plt.figure(figsize=(8, 5))
plt.bar(cobertura_ano["ano"].astype(str), cobertura_ano["qtd_registros"])
plt.xlabel("Ano")
plt.ylabel("Quantidade de registros")
plt.title("Quantidade de registros por ano")
plt.show()

/var/folders/m9/41dfdw417w50w33q_xckq5qh0000gp/T/ipykernel_15608/2350162331.py:6: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [24]:
cobertura_mes = (
    df.groupby(["ano", "mes_numero", "mes"])
    .size()
    .reset_index(name="qtd_registros")
    .sort_values(["ano", "mes_numero"])
)

cobertura_mes.head(20)

     ano  mes_numero  mes  qtd_registros
0   2021           1  JAN             33
1   2021           2  FEV             33
2   2021           3  MAR             33
3   2021           4  ABR             33
4   2021           5  MAI             33
5   2021           6  JUN             33
6   2021           7  JUL             33
7   2021           8  AGO             26
8   2021           9  SET             33
9   2021          10  OUT             33
10  2021          11  NOV             33
11  2021          12  DEZ             33
12  2022           1  JAN             33
13  2022           2  FEV             33
14  2022           3  MAR             33
15  2022           4  ABR             33
16  2022           5  MAI             33
17  2022           6  JUN             33
18  2022           7  JUL             33
19  2022           8  AGO             26

## 9. Composição por categoria e subcategoria

Esta análise mostra a composição estrutural da base, ou seja, quantos registros existem em cada área de indicadores.

In [25]:
categoria_resumo = (
    df.groupby("categoria")
    .agg(
        qtd_registros=("valor", "count"),
        qtd_indicadores=("indicador_completo", "nunique"),
        total_valor=("valor", "sum")
    )
    .reset_index()
    .sort_values("qtd_registros", ascending=False)
)

categoria_resumo

            categoria  qtd_registros  qtd_indicadores  total_valor
0            EDUCAÇÃO            436                9        593.0
1  PROFISSIONALIZAÇÃO            240                4       1092.0
2               SAÚDE            174                3       2368.0

In [26]:
plt.figure(figsize=(10, 5))
plt.barh(categoria_resumo["categoria"], categoria_resumo["qtd_registros"])
plt.xlabel("Quantidade de registros")
plt.ylabel("Categoria")
plt.title("Quantidade de registros por categoria")
plt.gca().invert_yaxis()
plt.show()

/var/folders/m9/41dfdw417w50w33q_xckq5qh0000gp/T/ipykernel_15608/366193340.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [27]:
subcategoria_resumo = (
    df.dropna(subset=["subcategoria"])
    .groupby(["categoria", "subcategoria"])
    .agg(
        qtd_registros=("valor", "count"),
        qtd_indicadores=("indicador_completo", "nunique"),
        total_valor=("valor", "sum")
    )
    .reset_index()
    .sort_values(["categoria", "subcategoria"])
)

subcategoria_resumo

  categoria     subcategoria  qtd_registros  qtd_indicadores  total_valor
0  EDUCAÇÃO       Ensino EJA             95                2         11.0
1  EDUCAÇÃO  Ensino infantil             94                2         99.0
2  EDUCAÇÃO   Ensino regular            100                2        260.0
3  EDUCAÇÃO             SCFV            147                3        223.0

## 10. Estatísticas descritivas da variável `valor`

A coluna `valor` concentra os registros numéricos mensais dos indicadores.

In [28]:
df["valor"].describe().to_frame().T

        count      mean        std  min  25%  50%   75%   max
valor  1862.0  8.042427  12.518222  0.0  0.0  2.0  12.0  87.0

In [29]:
plt.figure(figsize=(10, 5))
plt.hist(df["valor"].dropna(), bins=30)
plt.xlabel("Valor")
plt.ylabel("Frequência")
plt.title("Distribuição geral dos valores registrados")
plt.show()

/var/folders/m9/41dfdw417w50w33q_xckq5qh0000gp/T/ipykernel_15608/3603099563.py:6: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [30]:
plt.figure(figsize=(10, 5))
plt.boxplot(df["valor"].dropna(), vert=False)
plt.xlabel("Valor")
plt.title("Boxplot geral da variável valor")
plt.show()

/var/folders/m9/41dfdw417w50w33q_xckq5qh0000gp/T/ipykernel_15608/632793690.py:5: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## 11. Valores zerados

Como os indicadores são mensais, valores iguais a zero podem representar ausência de ocorrência no mês. Esta verificação ajuda a entender a proporção de zeros no dataset.

In [31]:
qtd_zeros = (df["valor"] == 0).sum()
percentual_zeros = round(qtd_zeros / len(df) * 100, 2)

pd.DataFrame({
    "métrica": ["Quantidade de valores zero", "Percentual de valores zero"],
    "valor": [qtd_zeros, percentual_zeros]
})

                      métrica   valor
0  Quantidade de valores zero  744.00
1  Percentual de valores zero   39.96

In [32]:
zeros_por_categoria = (
    df.assign(valor_zero=df["valor"] == 0)
    .groupby("categoria")
    .agg(
        qtd_registros=("valor", "count"),
        qtd_zeros=("valor_zero", "sum")
    )
    .reset_index()
)

zeros_por_categoria["percentual_zeros"] = (
    zeros_por_categoria["qtd_zeros"] / zeros_por_categoria["qtd_registros"] * 100
).round(2)

zeros_por_categoria.sort_values("percentual_zeros", ascending=False)

            categoria  qtd_registros  qtd_zeros  percentual_zeros
0            EDUCAÇÃO            436        327             75.00
1  PROFISSIONALIZAÇÃO            240        150             62.50
2               SAÚDE            174         41             23.56

In [33]:
zeros_plot = zeros_por_categoria.sort_values("percentual_zeros", ascending=True)

plt.figure(figsize=(10, 5))
plt.barh(zeros_plot["categoria"], zeros_plot["percentual_zeros"])
plt.xlabel("Percentual de valores zero (%)")
plt.ylabel("Categoria")
plt.title("Percentual de valores zero por categoria")
plt.show()

/var/folders/m9/41dfdw417w50w33q_xckq5qh0000gp/T/ipykernel_15608/427298107.py:8: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## 12. Cardinalidade das variáveis categóricas

A cardinalidade mostra quantos valores distintos existem em cada coluna categórica. Isso ajuda a entender quais campos funcionam bem como filtros no futuro dashboard.

In [34]:
colunas_categoricas = ["mes", "categoria", "subcategoria", "indicador", "indicador_completo"]

cardinalidade = pd.DataFrame({
    "coluna": colunas_categoricas,
    "valores_distintos": [df[col].nunique(dropna=True) for col in colunas_categoricas]
})

cardinalidade

               coluna  valores_distintos
0                 mes                 12
1           categoria                  3
2        subcategoria                  4
3           indicador                 27
4  indicador_completo                 33

In [35]:
plt.figure(figsize=(10, 5))
plt.bar(cardinalidade["coluna"], cardinalidade["valores_distintos"])
plt.xlabel("Coluna")
plt.ylabel("Quantidade de valores distintos")
plt.title("Cardinalidade das variáveis categóricas")
plt.xticks(rotation=45, ha="right")
plt.show()

/var/folders/m9/41dfdw417w50w33q_xckq5qh0000gp/T/ipykernel_15608/3660979843.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()