# TE - Visualização de Dados

**ONG:** Pão dos Pobres

**Grupo:**
- Ana Carolina Poletto
- Bárbara Dapper
- Louise Northfleet 
- Luiza Pasini
- Rafaela Remião

## 1. Leitura dos dados

In [ ]:
#IMPORTS

import pandas as pd
import numpy as np

from pathlib import Path
import os
import re

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

In [ ]:
#CARREGANDO OS DADOS

arquivos_excel = list(Path.cwd().rglob("*.xlsx"))

print(f"Foram encontrados {len(arquivos_excel)} arquivos Excel")

pasta_dados = arquivos_excel[0].parent

planilhas = {}

for arquivo in arquivos_excel:
    planilhas[arquivo.name] = pd.read_excel(arquivo)

print("Arquivos carregados com sucesso!")

Foram encontrados 9 arquivos Excel:
Arquivos carregados com sucesso!

In [14]:
#INSPEÇÃO

resumo_abas = []

for arquivo in arquivos_excel:
    excel = pd.ExcelFile(arquivo)

    for aba in excel.sheet_names:
        df = pd.read_excel(arquivo, sheet_name=aba)

        resumo_abas.append({
            "arquivo": arquivo.name,
            "aba": aba,
            "linhas": df.shape[0],
            "colunas": df.shape[1],
            "nomes_colunas": list(df.columns)
        })

resumo_abas_df = pd.DataFrame(resumo_abas)

resumo_abas_df

                         arquivo                              aba  linhas  colunas                                      nomes_colunas
0   LEM anual 2025 completo.xlsx    dados de informação gerencial      25       16  [Unnamed: 0, Unnamed: 1, Unnamed: 2, Unnamed: ...
1   LEM anual 2025 completo.xlsx             atividades culturais      78        5  [atividades lúdicas/recreativas/culturais. Faz...
2   LEM anual 2025 completo.xlsx            capacitações equipes       25        5  [capacitações Equipes.  Fazer uma breve relato...
3   LEM anual 2025 completo.xlsx        capacitações coordenações      29        5  [capacitações coordenações. Fazer uma breve re...
4   LEM anual 2025 completo.xlsx  participaçãoespaços de controle       1        5  [Participação em espaços de controle social (c...
5                  LEM 2021.xlsx                        Planilha1      43       21  [LEM - Levantamento estatístico Mensal/2021, U...
6                  LEM 2024.xlsx                        Planilha1      42       21  [LEM - Levantamento estatístico Mensal/2024, U...
7              LEM 2025 (3).xlsx                        Planilha1      42       21  [LEM - Levantamento Estatístico Mensal/2025, U...
8              LEM 2025 (3).xlsx                            Plan1       0        0                                                 []
9              LEM 2024 (1).xlsx                        Planilha1      42       21  [LEM - Levantamento Estatístico Mensal/2024, U...
10             LEM 2024 (1).xlsx                            Plan1       0        0                                                 []
11             LEM 2022 (1).xlsx                        Planilha1      42       21  [LEM - Levantamento estatístico Mensal/2022, U...
12                 LEM 2023.xlsx                        Planilha1      42       21  [LEM - Levantamento estatístico Mensal/2023, U...
13                 LEM 2023.xlsx                            Plan1       0        0                                                 []
14               LEM 2025 1.xlsx                        Planilha1      42       21  [LEM - Levantamento Estatístico Mensal/2025, U...
15               LEM 2025 1.xlsx                            Plan1       0        0                                                 []
16             LEM 2025 (2).xlsx                        Planilha1      42       21  [LEM - Levantamento Estatístico Mensal/2025, U...
17             LEM 2025 (2).xlsx                            Plan1       0        0                                                 []

In [15]:
for arquivo in arquivos_excel:
    excel = pd.ExcelFile(arquivo)

    for aba in excel.sheet_names:
        df = pd.read_excel(arquivo, sheet_name=aba)

        print(f"\nArquivo: {arquivo.name} | Aba: {aba}")
        display(df.head())

Arquivo: LEM anual 2025 completo.xlsx | Aba: dados de informação gerencial

                                          Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12  Unnamed: 13  Unnamed: 14  Unnamed: 15
0                     Dados de informações gerenc...        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN         NaN         NaN         NaN          NaN          NaN          NaN
1                                                NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN         NaN         NaN         NaN          NaN          NaN          NaN
2                     dados gerencias de efetividade        JAN        FEV        MAR        ABR        MAI        JUN        JUL        AGO        SET         OUT         NOV         DEZ          NaN          NaN          NaN
3  ADOLESCENTES INSERIDOS em cursos profissionali...          1          6          6          6          5          5          4          4          4           2           2         NaN          NaN          NaN        654.0
4      ADOLESCENTES INSERIDOS no mercado de trabalho          0          0          0          0          0          0          0          0          0           0           0         NaN          NaN          NaN          NaN

Arquivo: LEM anual 2025 completo.xlsx | Aba: atividades culturais

  atividades lúdicas/recreativas/culturais. Fazer uma breve resenha da atividade, número de participantes e registro de fotos.                  Unnamed: 1                                         Unnamed: 2               Unnamed: 3      Unnamed: 4
0                                                mês                                                                                                 local                         breve resenha da atividade  número de participantes  pasta de fotos
1                                            Janeiro                                                                            Colônia de Férias Cidreira  1 semana de férias na colônica dO Pão dos Pobr...                        5             NaN
2                                                NaN                                                                                                 ARM02                                  Aula de Culinária                       17             NaN
3                                                NaN                                                                                        Orla do Guaíba                                     Jogos noturnos                       17             NaN
4                                                NaN                                                                                                 ARM02                      Decoração da casa com pintura                       17             NaN

Arquivo: LEM anual 2025 completo.xlsx | Aba: capacitações equipes

  capacitações Equipes.  Fazer uma breve relato do tema, destacando local e carga horária. Unnamed: 1                                         Unnamed: 2       Unnamed: 3      Unnamed: 4
0                                                mês                                            local                               breve relato do tema      Colaborador  carga horária
1                                              Julho                                               MP                              Seminário 35 anos ECA  Camila e Glória              6h
2                                               Maio                                             CEAF  Acolhimento Institucional: Estratégicas para o...              NaN              3h
3                                                NaN                                              NaN                                                NaN              NaN             NaN
4                                                NaN                                              NaN                                                NaN              NaN             NaN

Arquivo: LEM anual 2025 completo.xlsx | Aba: capacitações coordenações

  capacitações coordenações. Fazer uma breve relato do tema, destacando local e carga horária.           Unnamed: 1                                         Unnamed: 2     Unnamed: 3      Unnamed: 4
0                                                mês                                                          local                               breve relato do tema    Colaborador  carga horária
1                                              Março                                             Quinta da Estância  Encontro formativo do grupo La Salle Equipe Local  Luis Fernando              6h
2                                              Julho                                            Sede Pão dos Pobres       Formação em Justiça Restaurativa- 5 encotros  Luis Fernando             15h
3                                                NaN                                                            NaN                                                NaN            NaN             NaN
4                                                NaN                                                            NaN                                                NaN            NaN             NaN

Arquivo: LEM anual 2025 completo.xlsx | Aba: participaçãoespaços de controle

  Participação em espaços de controle social (conselhos { CMDCA, CMAS, CORAS}, Fóruns permanentes, Fóruns extraordinários, representações) Unnamed: 1                                         Unnamed: 2   Unnamed: 3      Unnamed: 4
0                                                mês                                                                                            local  espaços de controle social (conselhos { CMDCA,...  Colaborador  carga horária

Arquivo: LEM 2021.xlsx | Aba: Planilha1

  LEM - Levantamento estatístico Mensal/2021 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12  Unnamed: 13  Unnamed: 14              Unnamed: 15  Unnamed: 16  Unnamed: 17  Unnamed: 18 Unnamed: 19 Unnamed: 20
0                                        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN         NaN         NaN         NaN          NaN          NaN                      NaN          NaN          NaN          NaN         NaN         NaN
1                    DESDOBRAMENTOS TÉCNICOS        JAN        FEV        MAR        ABR        MAI        JUN        JUL        AGO        SET         OUT         NOV         DEZ          NaN          NaN  desdobramentos técnicos          NaN          NaN          NaN         NaN         NaN
2                     Atendimentos indvidual         40         28         41         10         51         61         48         40         62          58          58          58        555.0          NaN                     1892          NaN          NaN          NaN         NaN         NaN
3                        Atedimento familiar         31          6         27          5         13         28         23         26         29          24          24          24        260.0          NaN                      NaN          NaN          NaN          NaN         NaN         NaN
4      Interface com rede socioassistencial          10         15         12          7         15         20         18          8         20          12          15          12        164.0          NaN                      NaN          NaN          NaN          NaN         NaN         NaN

Arquivo: LEM 2024.xlsx | Aba: Planilha1

  LEM - Levantamento estatístico Mensal/2024 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12  Unnamed: 13  Unnamed: 14              Unnamed: 15  Unnamed: 16  Unnamed: 17  Unnamed: 18 Unnamed: 19 Unnamed: 20
0                                        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN         NaN         NaN         NaN          NaN          NaN                      NaN          NaN          NaN          NaN         NaN         NaN
1                    DESDOBRAMENTOS TÉCNICOS        JAN        FEV        MAR        ABR        MAI        JUN        JUL        AGO        SET         OUT         NOV         DEZ          NaN          NaN  desdobramentos técnicos          NaN          NaN          NaN         NaN         NaN
2                     Atendimentos indvidual         39         79         54         39         58         87         62         69         70          68         NaN         NaN        625.0          NaN                     1994          NaN          NaN          NaN         NaN         NaN
3                        Atedimento familiar         36         37         33         26         29         25         31         27         34          39         NaN         NaN        317.0          NaN                      NaN          NaN          NaN          NaN         NaN         NaN
4      Interface com rede socioassistencial          18         20         23          9         19         13         13          9         12          16         NaN         NaN        152.0          NaN                      NaN          NaN          NaN          NaN         NaN         NaN

Arquivo: LEM 2025 (3).xlsx | Aba: Planilha1

  LEM - Levantamento Estatístico Mensal/2025 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12  Unnamed: 13  Unnamed: 14              Unnamed: 15  Unnamed: 16  Unnamed: 17  Unnamed: 18 Unnamed: 19 Unnamed: 20
0                                        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN         NaN         NaN         NaN          NaN          NaN                      NaN          NaN          NaN          NaN         NaN         NaN
1                    DESDOBRAMENTOS TÉCNICOS        JAN        FEV        MAR        ABR        MAI        JUN        JUL        AGO        SET         OUT         NOV         DEZ          NaN          NaN  desdobramentos técnicos          NaN          NaN          NaN         NaN         NaN
2                     Atendimentos indvidual         32         17         44         52         49         51         39         56         56          41          52          49          NaN          NaN                        0          NaN          NaN          NaN         NaN         NaN
3                        Atedimento familiar         20          3          1         20         29         33         28         32         32          33          20          29          NaN          NaN                      NaN          NaN          NaN          NaN         NaN         NaN
4      Interface com rede socioassistencial          10          6         20         10         20         22         19         23         25          20          10          20          NaN          NaN                      NaN          NaN          NaN          NaN         NaN         NaN

Arquivo: LEM 2025 (3).xlsx | Aba: Plan1

Empty DataFrame
Columns: []
Index: []

Arquivo: LEM 2024 (1).xlsx | Aba: Planilha1

  LEM - Levantamento Estatístico Mensal/2024 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12  Unnamed: 13  Unnamed: 14              Unnamed: 15  Unnamed: 16  Unnamed: 17  Unnamed: 18 Unnamed: 19 Unnamed: 20
0                                        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN         NaN         NaN         NaN          NaN          NaN                      NaN          NaN          NaN          NaN         NaN         NaN
1                    DESDOBRAMENTOS TÉCNICOS        JAN        FEV        MAR        ABR        MAI        JUN        JUL        AGO        SET         OUT         NOV         DEZ          NaN          NaN  desdobramentos técnicos          NaN          NaN          NaN         NaN         NaN
2                     Atendimentos indvidual         62         58         65         78         50         57         60         69         75          26          49          52        701.0          NaN                        0          NaN          NaN          NaN         NaN         NaN
3                        Atedimento familiar         47         42         50         52         33         49         51         56         45           7          30          28        490.0          NaN                      NaN          NaN          NaN          NaN         NaN         NaN
4      Interface com rede socioassistencial          24         21         15         19         25         18         22         15         18          16          17          12        222.0          NaN                      NaN          NaN          NaN          NaN         NaN         NaN

Arquivo: LEM 2024 (1).xlsx | Aba: Plan1

Empty DataFrame
Columns: []
Index: []

Arquivo: LEM 2022 (1).xlsx | Aba: Planilha1

  LEM - Levantamento estatístico Mensal/2022 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12  Unnamed: 13  Unnamed: 14              Unnamed: 15  Unnamed: 16  Unnamed: 17  Unnamed: 18 Unnamed: 19 Unnamed: 20
0                                        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN         NaN         NaN         NaN          NaN          NaN                      NaN          NaN          NaN          NaN         NaN         NaN
1                    DESDOBRAMENTOS TÉCNICOS        JAN        FEV        MAR        ABR        MAI        JUN        JUL        AGO        SET         OUT         NOV         DEZ          NaN          NaN  desdobramentos técnicos          NaN          NaN          NaN         NaN         NaN
2                     Atendimentos indvidual         40         28         41         10         51         61         48         40         62          58          63          60        562.0          NaN                     1984          NaN          NaN          NaN         NaN         NaN
3                        Atedimento familiar         31          6         27          5         13         28         23         26         29          24          35          34        281.0          NaN                      NaN          NaN          NaN          NaN         NaN         NaN
4      Interface com rede socioassistencial          10         15         12          7         15         20         18          8         20          12          17          18        172.0          NaN                      NaN          NaN          NaN          NaN         NaN         NaN

Arquivo: LEM 2023.xlsx | Aba: Planilha1

  LEM - Levantamento estatístico Mensal/2023 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12  Unnamed: 13  Unnamed: 14              Unnamed: 15  Unnamed: 16  Unnamed: 17  Unnamed: 18 Unnamed: 19 Unnamed: 20
0                                        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN         NaN         NaN         NaN          NaN          NaN                      NaN          NaN          NaN          NaN         NaN         NaN
1                    DESDOBRAMENTOS TÉCNICOS        JAN        FEV        MAR        ABR        MAI        JUN        JUL        AGO        SET         OUT         NOV         DEZ          NaN          NaN  desdobramentos técnicos          NaN          NaN          NaN         NaN         NaN
2                     Atendimentos indvidual         39         79         54         39         58         87         62         69         70          68          63          62        750.0          NaN                     2431          NaN          NaN          NaN         NaN         NaN
3                        Atedimento familiar         36         37         33         26         29         25         31         27         34          39          44          31        392.0          NaN                      NaN          NaN          NaN          NaN         NaN         NaN
4      Interface com rede socioassistencial          18         20         23          9         19         13         13          9         12          16          15          13        180.0          NaN                      NaN          NaN          NaN          NaN         NaN         NaN

Arquivo: LEM 2023.xlsx | Aba: Plan1

Empty DataFrame
Columns: []
Index: []

Arquivo: LEM 2025 1.xlsx | Aba: Planilha1

  LEM - Levantamento Estatístico Mensal/2025 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12  Unnamed: 13  Unnamed: 14              Unnamed: 15  Unnamed: 16  Unnamed: 17  Unnamed: 18 Unnamed: 19 Unnamed: 20
0                                        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN         NaN         NaN         NaN          NaN          NaN                      NaN          NaN          NaN          NaN         NaN         NaN
1                    DESDOBRAMENTOS TÉCNICOS        JAN        FEV        MAR        ABR        MAI        JUN        JUL        AGO        SET         OUT         NOV         DEZ          NaN          NaN  desdobramentos técnicos          NaN          NaN          NaN         NaN         NaN
2                     Atendimentos indvidual         53         42         56         52         49         65         66         63         60          70          49          66          NaN          NaN                        0          NaN          NaN          NaN         NaN         NaN
3                        Atedimento familiar         24         27         31         28         25         36         32         48         18          50          25          32          NaN          NaN                      NaN          NaN          NaN          NaN         NaN         NaN
4      Interface com rede socioassistencial           9         11         12         13         12         17          9         26         25          28          12           9          NaN          NaN                      NaN          NaN          NaN          NaN         NaN         NaN

Arquivo: LEM 2025 1.xlsx | Aba: Plan1

Empty DataFrame
Columns: []
Index: []

Arquivo: LEM 2025 (2).xlsx | Aba: Planilha1

  LEM - Levantamento Estatístico Mensal/2025 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12  Unnamed: 13  Unnamed: 14              Unnamed: 15  Unnamed: 16  Unnamed: 17  Unnamed: 18 Unnamed: 19 Unnamed: 20
0                                        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN         NaN         NaN         NaN          NaN          NaN                      NaN          NaN          NaN          NaN         NaN         NaN
1                    DESDOBRAMENTOS TÉCNICOS        JAN        FEV        MAR        ABR        MAI        JUN        JUL        AGO        SET         OUT         NOV         DEZ          NaN          NaN  desdobramentos técnicos          NaN          NaN          NaN         NaN         NaN
2                     Atendimentos indvidual         32         17         44         52         49         51         39        NaN        NaN         NaN         NaN         NaN          NaN          NaN                        0          NaN          NaN          NaN         NaN         NaN
3                        Atedimento familiar         20          3          1         20         29         33         28        NaN        NaN         NaN         NaN         NaN          NaN          NaN                      NaN          NaN          NaN          NaN         NaN         NaN
4      Interface com rede socioassistencial          10          6         20         10         20         22         19        NaN        NaN         NaN         NaN         NaN          NaN          NaN                      NaN          NaN          NaN          NaN         NaN         NaN

Arquivo: LEM 2025 (2).xlsx | Aba: Plan1

Empty DataFrame
Columns: []
Index: []

## 2. Limpeza dos dados

In [31]:
# Meses utilizados nas planilhas
meses = ["JAN", "FEV", "MAR", "ABR", "MAI", "JUN", "JUL", "AGO", "SET", "OUT", "NOV", "DEZ"]

mapa_meses = {
    "JAN": 1,
    "FEV": 2,
    "MAR": 3,
    "ABR": 4,
    "MAI": 5,
    "JUN": 6,
    "JUL": 7,
    "AGO": 8,
    "SET": 9,
    "OUT": 10,
    "NOV": 11,
    "DEZ": 12
}

categorias_lem = [
    "DESDOBRAMENTOS TÉCNICOS",
    "PROFISSIONALIZAÇÃO",
    "SAÚDE",
    "EDUCAÇÃO"
]

In [32]:
def extrair_ano(nome_arquivo):
    match = re.search(r"20\d{2}", nome_arquivo)
    return int(match.group()) if match else None

In [33]:
def limpar_texto(texto):
    if pd.isna(texto):
        return None
    
    texto = str(texto).strip()
    texto = re.sub(r"\s+", " ", texto)
    
    return texto

In [35]:
def encontrar_linha_cabecalho(df_bruto):
    """
    Procura a linha que contém os meses JAN, FEV, MAR...
    """
    for indice, linha in df_bruto.iterrows():
        valores_linha = [limpar_texto(valor) for valor in linha.values]
        valores_linha = [valor for valor in valores_linha if valor is not None]

        qtd_meses = sum(valor in meses for valor in valores_linha)

        if qtd_meses >= 3:
            return indice

    return None

In [36]:
def adicionar_categoria(df):
    categoria_atual = None
    categorias = []

    for indicador in df["indicador"]:
        indicador_limpo = limpar_texto(indicador)

        if indicador_limpo is not None and indicador_limpo.upper() in categorias_lem:
            categoria_atual = indicador_limpo.upper()
            categorias.append(categoria_atual)
        else:
            categorias.append(categoria_atual)

    df["categoria"] = categorias

    # Remove linhas que são somente títulos de categoria
    df = df[
        ~df["indicador"]
        .astype(str)
        .str.upper()
        .isin(categorias_lem)
    ]

    return df

In [37]:
def ler_lem_mensal(arquivo):
    ano = extrair_ano(arquivo.name)

    # Lê a planilha sem cabeçalho para encontrar onde estão os meses
    df_bruto = pd.read_excel(
        arquivo,
        sheet_name="Planilha1",
        header=None
    )

    linha_cabecalho = encontrar_linha_cabecalho(df_bruto)

    if linha_cabecalho is None:
        raise ValueError("Não foi possível encontrar a linha de cabeçalho com os meses.")

    # Define a linha encontrada como cabeçalho
    novo_cabecalho = df_bruto.iloc[linha_cabecalho].apply(limpar_texto).tolist()

    # Dados começam na linha seguinte ao cabeçalho
    df = df_bruto.iloc[linha_cabecalho + 1:].copy()
    df.columns = novo_cabecalho

    # Renomeia a primeira coluna para indicador
    df = df.rename(columns={df.columns[0]: "indicador"})

    # Limpa nomes das colunas
    df.columns = [limpar_texto(col) for col in df.columns]

    # Mantém apenas indicador + meses
    colunas_meses_existentes = [mes for mes in meses if mes in df.columns]

    if len(colunas_meses_existentes) == 0:
        raise ValueError("Nenhuma coluna de mês foi encontrada.")

    df = df[["indicador"] + colunas_meses_existentes]

    # Remove linhas vazias
    df = df.dropna(how="all")
    df = df.dropna(subset=["indicador"])

    # Limpa os nomes dos indicadores
    df["indicador"] = df["indicador"].apply(limpar_texto)

    # Adiciona categoria
    df = adicionar_categoria(df)

    # Transforma de formato largo para longo
    df_longo = df.melt(
        id_vars=["categoria", "indicador"],
        value_vars=colunas_meses_existentes,
        var_name="mes",
        value_name="valor"
    )

    # Adiciona informações auxiliares
    df_longo["ano"] = ano
    df_longo["mes_numero"] = df_longo["mes"].map(mapa_meses)
    df_longo["fonte_arquivo"] = arquivo.name

    # Remove valores vazios
    df_longo = df_longo.dropna(subset=["valor"])

    # Converte para número
    df_longo["valor"] = pd.to_numeric(df_longo["valor"], errors="coerce")

    # Remove valores não numéricos, como X
    df_longo = df_longo.dropna(subset=["valor"])

    # Organiza colunas
    df_longo = df_longo[
        [
            "ano",
            "mes",
            "mes_numero",
            "categoria",
            "indicador",
            "valor",
            "fonte_arquivo"
        ]
    ]

    return df_longo

In [38]:
arquivos_lem_mensal = [
    arquivo for arquivo in arquivos_excel
    if "anual" not in arquivo.name.lower()
]

bases_lem = []

for arquivo in arquivos_lem_mensal:
    try:
        df_tratado = ler_lem_mensal(arquivo)
        bases_lem.append(df_tratado)
        print(f"Arquivo processado com sucesso: {arquivo.name} | {df_tratado.shape[0]} linhas")
    except Exception as erro:
        print(f"Erro ao processar {arquivo.name}: {erro}")

Arquivo processado com sucesso: LEM 2021.xlsx | 390 linhas
Arquivo processado com sucesso: LEM 2024.xlsx | 217 linhas
Arquivo processado com sucesso: LEM 2025 (3).xlsx | 386 linhas
Arquivo processado com sucesso: LEM 2024 (1).xlsx | 393 linhas
Arquivo processado com sucesso: LEM 2022 (1).xlsx | 389 linhas
Arquivo processado com sucesso: LEM 2023.xlsx | 304 linhas
Arquivo processado com sucesso: LEM 2025 1.xlsx | 360 linhas
Arquivo processado com sucesso: LEM 2025 (2).xlsx | 231 linhas

In [39]:
lem_consolidado = pd.concat(bases_lem, ignore_index=True)

lem_consolidado.head(20)

     ano  mes  mes_numero           categoria                                          indicador  valor  fonte_arquivo
0   2021  JAN           1                 NaN                             Atendimentos indvidual   40.0  LEM 2021.xlsx
1   2021  JAN           1                 NaN                                Atedimento familiar   31.0  LEM 2021.xlsx
2   2021  JAN           1                 NaN               Interface com rede socioassistencial   10.0  LEM 2021.xlsx
3   2021  JAN           1                 NaN                           Interface com judiciário    8.0  LEM 2021.xlsx
4   2021  JAN           1                 NaN                                Interface com saúde   18.0  LEM 2021.xlsx
5   2021  JAN           1                 NaN                             Interface com educação    9.0  LEM 2021.xlsx
6   2021  JAN           1                 NaN                                  PIAS / Relatórios   17.0  LEM 2021.xlsx
7   2021  JAN           1                 NaN                               Visitas Domiciliares    2.0  LEM 2021.xlsx
8   2021  JAN           1                 NaN                             Apadrinhamento afetivo    0.0  LEM 2021.xlsx
9   2021  JAN           1                 NaN                    Colocação em família substituta    0.0  LEM 2021.xlsx
10  2021  JAN           1                 NaN  Reunião de equipe (técnica, casa, coordenação,...    6.0  LEM 2021.xlsx
11  2021  JAN           1                 NaN                                      Desligamentos    0.0  LEM 2021.xlsx
12  2021  JAN           1                 NaN                                             Evasão    2.0  LEM 2021.xlsx
13  2021  JAN           1                 NaN                                    Novos ingressos    0.0  LEM 2021.xlsx
14  2021  JAN           1                 NaN                                     Transferências    0.0  LEM 2021.xlsx
15  2021  JAN           1                 NaN                                   Efetivos na casa   15.0  LEM 2021.xlsx
16  2021  JAN           1                 NaN  Documentação civil (RG / CPF/ CTPS / Certidão ...    0.0  LEM 2021.xlsx
17  2021  JAN           1  PROFISSIONALIZAÇÃO              INSERIDOS em curso profissionalizante    0.0  LEM 2021.xlsx
18  2021  JAN           1  PROFISSIONALIZAÇÃO         ENCAMINHADOS para curso profissionalizante    0.0  LEM 2021.xlsx
19  2021  JAN           1  PROFISSIONALIZAÇÃO                    INSERIDO no mercado de trabalho    0.0  LEM 2021.xlsx

In [40]:
# Dimensão da base consolidada
lem_consolidado.shape

(2670, 7)

In [41]:
# Quantidade de registros por ano
lem_consolidado["ano"].value_counts().sort_index()

ano
2021    390
2022    389
2023    304
2024    610
2025    977
Name: count, dtype: int64

In [42]:
lem_consolidado[["ano", "mes", "categoria", "indicador", "valor", "fonte_arquivo"]].head(30)

     ano  mes           categoria                                          indicador  valor  fonte_arquivo
0   2021  JAN                 NaN                             Atendimentos indvidual   40.0  LEM 2021.xlsx
1   2021  JAN                 NaN                                Atedimento familiar   31.0  LEM 2021.xlsx
2   2021  JAN                 NaN               Interface com rede socioassistencial   10.0  LEM 2021.xlsx
3   2021  JAN                 NaN                           Interface com judiciário    8.0  LEM 2021.xlsx
4   2021  JAN                 NaN                                Interface com saúde   18.0  LEM 2021.xlsx
5   2021  JAN                 NaN                             Interface com educação    9.0  LEM 2021.xlsx
6   2021  JAN                 NaN                                  PIAS / Relatórios   17.0  LEM 2021.xlsx
7   2021  JAN                 NaN                               Visitas Domiciliares    2.0  LEM 2021.xlsx
8   2021  JAN                 NaN                             Apadrinhamento afetivo    0.0  LEM 2021.xlsx
9   2021  JAN                 NaN                    Colocação em família substituta    0.0  LEM 2021.xlsx
10  2021  JAN                 NaN  Reunião de equipe (técnica, casa, coordenação,...    6.0  LEM 2021.xlsx
11  2021  JAN                 NaN                                      Desligamentos    0.0  LEM 2021.xlsx
12  2021  JAN                 NaN                                             Evasão    2.0  LEM 2021.xlsx
13  2021  JAN                 NaN                                    Novos ingressos    0.0  LEM 2021.xlsx
14  2021  JAN                 NaN                                     Transferências    0.0  LEM 2021.xlsx
15  2021  JAN                 NaN                                   Efetivos na casa   15.0  LEM 2021.xlsx
16  2021  JAN                 NaN  Documentação civil (RG / CPF/ CTPS / Certidão ...    0.0  LEM 2021.xlsx
17  2021  JAN  PROFISSIONALIZAÇÃO              INSERIDOS em curso profissionalizante    0.0  LEM 2021.xlsx
18  2021  JAN  PROFISSIONALIZAÇÃO         ENCAMINHADOS para curso profissionalizante    0.0  LEM 2021.xlsx
19  2021  JAN  PROFISSIONALIZAÇÃO                    INSERIDO no mercado de trabalho    0.0  LEM 2021.xlsx
20  2021  JAN  PROFISSIONALIZAÇÃO               ENCAMINHADO para mercado de trabalho    0.0  LEM 2021.xlsx
21  2021  JAN               SAÚDE                                       Saude mental   27.0  LEM 2021.xlsx
22  2021  JAN               SAÚDE                                      Saúde Clínica   11.0  LEM 2021.xlsx
23  2021  JAN               SAÚDE                                        Internações    0.0  LEM 2021.xlsx
24  2021  JAN            EDUCAÇÃO                                       matriculados    2.0  LEM 2021.xlsx
25  2021  JAN            EDUCAÇÃO                                    aguardando vaga    3.0  LEM 2021.xlsx
26  2021  JAN            EDUCAÇÃO                                       matriculados   12.0  LEM 2021.xlsx
27  2021  JAN            EDUCAÇÃO                                    aguardando vaga    3.0  LEM 2021.xlsx
28  2021  JAN            EDUCAÇÃO                                       matriculados    0.0  LEM 2021.xlsx
29  2021  JAN            EDUCAÇÃO                                    aguardando vaga    0.0  LEM 2021.xlsx

In [43]:
# Cria uma pasta para os dados tratados
pasta_saida = Path("dados_tratados")
pasta_saida.mkdir(exist_ok=True)

# Salva a base consolidada
lem_consolidado.to_csv(
    pasta_saida / "lem_consolidado_2021_2025.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Base consolidada salva com sucesso!")

Base consolidada salva com sucesso!

## 3. Verificação da qualidade

In [44]:
lem_consolidado.info()

<class 'pandas.DataFrame'>
RangeIndex: 2670 entries, 0 to 2669
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ano            2670 non-null   int64
 1   mes            2670 non-null   str
 2   mes_numero     2670 non-null   int64
 3   categoria      1171 non-null   str
 4   indicador      2670 non-null   str
 5   valor          2670 non-null   float64
 6   fonte_arquivo  2670 non-null   str
dtypes: float64(1), int64(2), str(4)
memory usage: 146.1 KB

In [45]:
lem_consolidado["ano"].value_counts().sort_index()

ano
2021    390
2022    389
2023    304
2024    610
2025    977
Name: count, dtype: int64

In [46]:
lem_consolidado["mes"].value_counts()

mes
ABR    247
MAI    244
MAR    243
JUN    243
JUL    242
FEV    241
JAN    237
OUT    215
SET    213
AGO    205
NOV    170
DEZ    170
Name: count, dtype: int64

In [47]:
lem_consolidado["categoria"].value_counts()

categoria
EDUCAÇÃO              602
PROFISSIONALIZAÇÃO    318
SAÚDE                 251
Name: count, dtype: int64

In [48]:
lem_consolidado["indicador"].nunique()

30

In [49]:
lem_consolidado["indicador"].sort_values().unique()

<StringArray>
['Apadrinhamento afetivo', 'Atedimento familiar', 'Atendimentos indvidual', 'Colocação em família substituta', 'Desligamentos', 'Documentação civil (RG / CPF/ CTPS / Certidão de nascimento)', 'ENCAMINHADO para mercado de trabalho', 'ENCAMINHADOS para curso profissionalizante', 'Efetivos na casa', 'Ensino EJA', 'Ensino infantil', 'Ensino regular', 'Evasão', 'INSERIDO no mercado de trabalho', 'INSERIDOS em curso profissionalizante', 'Interface com educação', 'Interface com judiciário', 'Interface com rede socioassistencial', 'Interface com saúde', 'Internações', 'Novos ingressos', 'Outros: Reforço escolar, psicopedagoga, trabalho educativo', 'PIAS / Relatórios', 'Reunião de equipe (técnica, casa, coordenação, gerente)', 'Saude mental', 'Saúde Clínica', 'Transferências', 'Visitas Domiciliares', 'aguardando vaga', 'matriculados']
Length: 30, dtype: str

## 4. Tratamento de duplicatas e Padronização

In [50]:
lem_consolidado["fonte_arquivo"].value_counts()

fonte_arquivo
LEM 2024 (1).xlsx    393
LEM 2021.xlsx        390
LEM 2022 (1).xlsx    389
LEM 2025 (3).xlsx    386
LEM 2025 1.xlsx      360
LEM 2023.xlsx        304
LEM 2025 (2).xlsx    231
LEM 2024.xlsx        217
Name: count, dtype: int64

In [ ]:
#VENDO DUPLICATAS 
totais_por_arquivo = (
    lem_consolidado
    .groupby(["ano", "fonte_arquivo"])["valor"]
    .sum()
    .reset_index()
    .sort_values(["ano", "fonte_arquivo"])
)

totais_por_arquivo

    ano      fonte_arquivo   valor
0  2021      LEM 2021.xlsx  2335.0
1  2022  LEM 2022 (1).xlsx  2360.0
2  2023      LEM 2023.xlsx  3760.0
3  2024  LEM 2024 (1).xlsx  3253.0
4  2024      LEM 2024.xlsx  2383.0
5  2025  LEM 2025 (2).xlsx  1763.0
6  2025  LEM 2025 (3).xlsx  3266.0
7  2025    LEM 2025 1.xlsx  3184.0

OBS: aqui mostra que os arquivos do mesmo ano tem quantiddes diferentes de informações, então precisamos escolher quais usar

In [52]:
for indicador in sorted(lem_consolidado["indicador"].unique()):
    print(indicador)

Apadrinhamento afetivo
Atedimento familiar
Atendimentos indvidual
Colocação em família substituta
Desligamentos
Documentação civil (RG / CPF/ CTPS / Certidão de nascimento)
ENCAMINHADO para mercado de trabalho
ENCAMINHADOS para curso profissionalizante
Efetivos na casa
Ensino EJA
Ensino infantil
Ensino regular
Evasão
INSERIDO no mercado de trabalho
INSERIDOS em curso profissionalizante
Interface com educação
Interface com judiciário
Interface com rede socioassistencial
Interface com saúde
Internações
Novos ingressos
Outros: Reforço escolar, psicopedagoga, trabalho educativo
PIAS / Relatórios
Reunião de equipe (técnica, casa, coordenação, gerente)
Saude mental
Saúde Clínica
Transferências
Visitas Domiciliares
aguardando vaga
matriculados

In [ ]:
#PADRONIZAÇÃO
mapa_indicadores = {
    "Atedimento familiar": "Atendimento familiar",
    "Saude mental": "Saúde mental",
    "PIAS / Relatórios": "PIAs / Relatórios",
    "ENCAMINHADO para mercado de trabalho": "Encaminhados para mercado de trabalho",
    "ENCAMINHADOS para curso profissionalizante": "Encaminhados para curso profissionalizante",
    "INSERIDO no mercado de trabalho": "Inseridos no mercado de trabalho",
    "INSERIDOS em curso profissionalizante": "Inseridos em curso profissionalizante",
}

In [54]:
lem_consolidado["indicador"] = lem_consolidado["indicador"].replace(mapa_indicadores)

In [55]:
for indicador in sorted(lem_consolidado["indicador"].unique()):
    print(indicador)

Apadrinhamento afetivo
Atendimento familiar
Atendimentos indvidual
Colocação em família substituta
Desligamentos
Documentação civil (RG / CPF/ CTPS / Certidão de nascimento)
Efetivos na casa
Encaminhados para curso profissionalizante
Encaminhados para mercado de trabalho
Ensino EJA
Ensino infantil
Ensino regular
Evasão
Inseridos em curso profissionalizante
Inseridos no mercado de trabalho
Interface com educação
Interface com judiciário
Interface com rede socioassistencial
Interface com saúde
Internações
Novos ingressos
Outros: Reforço escolar, psicopedagoga, trabalho educativo
PIAs / Relatórios
Reunião de equipe (técnica, casa, coordenação, gerente)
Saúde Clínica
Saúde mental
Transferências
Visitas Domiciliares
aguardando vaga
matriculados

## 5. Análise exploratória